### PR TITLE
LPS-59212 SF

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/8b1290da71...de0c823b29

**Comment by brianchandotcom** [comment]
@arbetts I made about 10 SF commits to this pull. Please review. Thx.

**Comment by brianchandotcom** [comment]
@arbetts also, ee-7.0.x? Thx.

**Comment by arbetts** [comment]
@brianchandotcom reviewing SF

will send pull for 7.0.x

**Comment by arbetts** [comment]
@brianchandotcom 

looks like you already committed changes to ee-7.0.x at gitId: b2aff15c3950f1c2a0f6d69624100ed6193ffc3a

was there another branch you wanted me to look at?

**Pull request closed without merging**
