### PR TITLE
LPS-70874

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/af303ec80f...1af5bd0730

**Comment by brianchandotcom** [comment]
@Ithildir @lawrence-lee please see my changes in upstream.

@Ithildir we need to Gradle the zip tools file for Central/Portal.

**Comment by lawrence-lee** [comment]
Thanks @brianchandotcom. Who should I send the backport to ee-7.0.x to?

**Comment by brianchandotcom** [comment]
@lawrence-lee I already did it.

**Comment by Ithildir** [comment]
Sorry @brianchandotcom, what do you mean in https://github.com/brianchandotcom/liferay-plugins/pull/5366#issuecomment-282355936? Do I need to do anything else?

**Comment by lawrence-lee** [comment]
@brianchandotcom Thanks!

**Pull request closed without merging**
