### PR TITLE
LPS-52584 - Web form field cannot be added when the site language settings are changed

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Apparently this was already merged on https://github.com/brianchandotcom/liferay-portal/pull/23503

**Comment by daviddotzhang** [comment]
@marcellustavares 

I just got a message from a QA,He said that LPS-52584 was not fixed. I found that this should not be closed, as it is a fix for plugin instead of  portal,they are not the same.

Thanks in advance.

**Comment by marcellustavares** [comment]
hi @daviddotzhang, is this commit still missing?

**Comment by daviddotzhang** [comment]
Hi @marcellustavares 

yes, this fix has,t been committed to plugin master .

**Comment by marcellustavares** [comment]
Got it, thx @daviddotzhang.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/fe29fa07fd...a13ea55660

**Comment by brianchandotcom** [comment]
Ok. I just merged iti n.. please backport if necessary @daviddotzhang

**Pull request closed without merging**
