### PR TITLE
LPS-51454

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Related to https://github.com/brianchandotcom/liferay-portal/pull/29607

**Comment by jonathanmccann** [comment]
Resent https://github.com/hhuijser/liferay-plugins/pull/283

**Comment by brianchandotcom** [comment]
@kiyoshilee same here

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/13d46827a9...5e565207b4

**Comment by brianchandotcom** [comment]
@jonathanmccann  I ran SF on a few of them. See upstream and please backport as necessary. Thx.

**Comment by kiyoshilee** [comment]
@brianchandotcom this error is different, the one in the plugins-ee repository is a result of a file not compiling in the lcs-portlet, this one is because of the opensocial portlet, see below:

<pre>    [javac] Compiling 62 source files to /opt/dev/projects/github/liferay-plugins/portlets/opensocial-portlet/docroot/WEB-INF/classes
    [javac] /opt/dev/projects/github/liferay-plugins/portlets/opensocial-portlet/docroot/WEB-INF/src/com/liferay/opensocial/shindig/service/LiferayPersonService.java:341: error: no suitable method found for getOffset()
    [javac] 				Long.valueOf(user.getTimeZone().getOffset()));
    [javac] 				                               ^
    [javac]     method TimeZone.getOffset(long) is not applicable
    [javac]       (actual and formal argument lists differ in length)
    [javac]     method TimeZone.getOffset(int,int,int,int,int,int) is not applicable
    [javac]       (actual and formal argument lists differ in length)
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error</pre>

**Pull request closed without merging**
