### PR TITLE
SYNC-1571

### PR DESCRIPTION
**Pull request by shinnlok**
ee-7.0.x - brianchandotcom/liferay-plugins-ee#17758
ee-6.2.x - brianchandotcom/liferay-plugins-ee#17757

### CODE REVIEW

**Comment by shinnlok** [comment]
ee-7.0.x - https://github.com/brianchandotcom/liferay-plugins-ee/pull/17758
ee-6.2.x - https://github.com/brianchandotcom/liferay-plugins-ee/pull/17757

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/411af26d7c...d867845117

**Comment by brianchandotcom** [comment]
@shinnlok I still need 6.2.x plugins.

For some reason that one didn't backport either.

**Comment by shinnlok** [comment]
https://github.com/brianchandotcom/liferay-plugins/pull/5229

**Pull request closed without merging**
