### PR TITLE
LPS-57200 apply assets change to KB [fixed]

### PR DESCRIPTION
**Pull request by juliocamarero**
cc @sergiogonzalez

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero doesn't compile?

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/3f6ff9f795...2146b5a916

**Pull request closed without merging**
