### PR TITLE
LPS-59312 SF

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/11f205e104...760d81e309

**Comment by brianchandotcom** [comment]
Nice job @leoadb @inacionery can you guys also check ee-7.0.x in liferay-plugins-ee ? I backported your commits there already. But there may be some EE only plugins in there that need to be updated too. Thx.

**Comment by inacionery** [comment]
@brianchandotcom Thanks. 
Yes, i'll create a subtask to fix them.

**Comment by inacionery** [comment]
@brianchandotcom i searched on ee-7.0.x in liferay-plugins-ee and there isn't deprecated methods.

**Pull request closed without merging**
