### PR TITLE
LPS-54435

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/c538dcac66...439c8a3d1e

**Comment by brianchandotcom** [comment]
@ambrinchaudhary please send me a pull to ee-7.0.x as well. Thx.

**Comment by brianchandotcom** [comment]
@ambrinchaudhary and also ee-6.2.x if necessary. Thx. I just cherry picked ee-7.0.x, so you may not have to send any changes for that.

**Comment by ambrinchaudhary** [comment]
Hi @brianchandotcom, 
on ee-6.2.x we are not using the taglib 'social-bookmarks-settings' and we need the toggle function call here, so this changes does not apply on that version. 
Thanks!

**Pull request closed without merging**
