### PR TITLE
LPS-58116 - Extract themes to individual OSGI modules

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Brian,

These are changes are for compiling themes in plugins with the new individual theme bundles.

This pull will probably fail the pull request tester because it will run against master, and the theme modules won't be there.

I'm going to ping @Ithildir so he can put this pull in his git-commit-plugins and send again so his pull will pass.

Thanks!

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/01baf13bf1...4ce352ac26

**Pull request closed without merging**
