### PR TITLE
SOS-2534

### PR DESCRIPTION
**Pull request by jcampoy**
[TECHNICAL SUPPORT] Hi Brian, testing this issue I've checked that we've missed an space between fields in the fix. Could you add this commit? Thank you. /cc @johnnyhowey

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/ce6159f95a...efeae6c45c

**Comment by brianchandotcom** [comment]
Please backport? Thx.

**Comment by jcampoy** [comment]
Yes, we've sent a new PR with all this code to the BPR team.

Thank you

**Comment by johnnyhowey** [comment]
Thanks!

**Pull request closed without merging**
