### PR TITLE
Lps 54867

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Oops, how come there are plugins with bnd.bnd ?

Figuring out a way to work around...

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Ugh, CI does not set correct liferay.home property for plugins build.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Finally made it working :)

CC @michaelhashimoto , see my last commit, please reset liferay.home to be same as app.server.parent.dir in build.properties, and override liferay.home to correct value from CI build script.

Thanks

**Comment by michaelhashimoto** [comment]
@shuyangzhou 

Here's a pull request to apply this change to jenkins as well:
https://github.com/brianchandotcom/liferay-jenkins-ee/pull/703

I'll change the defaults once jenkins has been updated.

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/0048672941...eda6fa5518

**Pull request closed without merging**
