### PR TITLE
LPS-55655

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/59c38c1db8...1bb50e75ae

**Comment by brianchandotcom** [comment]
@jonmak08 see 1228a6dd3a58b55a6451b9fcc567099ebbd45537

Thx

**Comment by brianchandotcom** [comment]
@westonhancock please backport. Thx.

**Comment by jonmak08** [comment]
Hey @brianchandotcom,

I have sent you another pull (https://github.com/brianchandotcom/liferay-plugins/pull/4632) to revert https://github.com/brianchandotcom/liferay-plugins/commit/1228a6dd3a58b55a6451b9fcc567099ebbd45537.

Please let me know if you have any questions.  Thanks!

**Comment by natecavanaugh** [comment]
@brianchandotcom We set a flag in our source formatting checker to remove extraneous parenthesis, which I'm working on trying to tweak, but the main issue is that we kept just having parens wrapping every bit of logic, even when it wasn't necessary, and was instead hampering legibility instead of improving it.
In JS there are order for conditional operations as well as with mathematical operations (such as MDAS), so when those operations are part of a standard set of behavior, the only consistent way to check it is if the operation is one that flows out of the order of operations.
For instance, `((x && y && b) && c)` would be redundant because it would be the same thing without the parenthesis, whereas, something like `(x && (y || a) && b)` would be different than `(x && y || a && b)` (since comparison such as `!= > ==` comes first, `&&` comes next, and `||` is last).

If you have any thoughts on it though, let me know.

**Pull request closed without merging**
