### PR TITLE
[FORWARD-PORT] LPS-50749 ant format-source

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/34d5b1ec4b...48a0c2dac1

**Comment by brianchandotcom** [comment]
@jrao please double check our changes in master and in ee-6.2.x. Thx.

**Comment by jrao** [comment]
@brianchandotcom, CC: @adolfopa, @jhinkey:

Double-checked your updates and tested on both master and ee-6.2.x using the steps listed in my comment to https://issues.liferay.com/browse/LPS-46838.

Everything is working as expected.

**Pull request closed without merging**
