### PR TITLE
LPS-61655

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/21dfbe1bfa...3663b448b3

**Comment by brianchandotcom** [comment]
@natecavanaugh LPS in commits and pull don't match. I'm using the ones from the commits.

**Comment by brianchandotcom** [comment]
@tylerwonglr good job on this. Please backport to ee-6.2.x with changes from Nate and Jon Mak. Thx.

**Comment by tylerwonglr** [comment]
@brianchandotcom Thanks Brian!  Will do!

**Pull request closed without merging**
