### PR TITLE
Lps 54867

### PR DESCRIPTION
**Pull request by shuyangzhou**
Since Matt and Will is going to come back next week, I will leave the backport to them.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou I merged this in, but if I know Ant, I think that your includes ignores docroot/view.jsp or src/META-INF/resources/*.jsp

Can you double check?

Thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/71883d71e7...918758bbf1

**Comment by shuyangzhou** [comment]
**/*.jsp means any file whose name ends with ".jsp" at any depth.

Tried on sample-jsp-portlet and amazon-rankings-web with debug scan output.
sample-jsp-portlet :
#########docroot/view.jsp

amazon-rankings-web :
#########src/META-INF/resources/configuration.jsp;src/META-INF/resources/init-ext.jsp;src/META-INF/resources/init.jsp;src/META-INF/resources/view.jsp

We should be fine.

**Pull request closed without merging**
