### PR TITLE
LPS-52680

### PR DESCRIPTION
**Pull request by johnnyhowey**

### CODE REVIEW

**Comment by johnnyhowey** [comment]
@IstvanD Please send the backport for this to ee-6.2.x if you want this fix for 6.2

**Comment by brianchandotcom** [comment]
@IstvanD I'd want it for ee-6.2.x and ee-6.2.10

Thx

**Comment by brianchandotcom** [comment]
This code is a bit weird.. can we avoid a do / while loop, and also avoid _start? We haven't had to do that anywhere else.

Thx

**Comment by johnnyhowey** [comment]
@IstvanD I sent you an email regarding this. :)

**Pull request closed without merging**
