### PR TITLE
Lps 54867

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Can you double check that

docroot/**/*.jsp matches docroot/view.jsp

docroot/**.jsp may not match docroot/hello/view.jsp

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/8145731eeb...2568d80fbc

**Comment by brianchandotcom** [comment]
Just need your help for 6.1. I did 7.0 and 6.2.

Thx!

**Comment by mtambara** [comment]
docroot/*/.jsp matches nothing

docroot/**.jsp matches docroot/view.jsp only

docroot/**/*.jsp matches both docroot/view.jsp and docroot/hello/view.jsp

**Pull request closed without merging**
