### PR TITLE
LPS-53747 Code coverage task for plugins SDK

### PR DESCRIPTION
**Pull request by mdelapenya**
Please review my changes, thanks!

cc/ @migue

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Hey @shuyangzhou does this mesh well with your custom cobertura-agent.jar in core? How would it relate?

**Comment by shuyangzhou** [comment]
Unfortunately this won't work with our cobertura agent.

Our agent is on cobertura 1.9.4.1, we have to use this version, can not simply just upgrade. As the new version completely changed the way how instrument is done(which is a very bad decision, this is the very only reason I choose cobertura over Emma and Jacoco in the first place), which making it impossible to do runtime re-instrument, therefore the main usage CodeCoverageAssertor will break. We can not accept that, we current have 388 very important infrastructure level 100% covered unit tests using it.

As a matter of fact the new version cobertura 2+ is no good at all, the only good thing it has is jdk7 reporting support(only for reporting, has nothing to do with its main function). Old version breaks on jdk7 classes reporting.

Fixing the jdk7 reporting is on my to do list, but with a very low priority, hopefully I can get into it by the end of this year.

Unless adding coverage report for modules is a critical thing to have immediately, it will be a wise thing to just leave it out for now. I will deal with it once I get a break.

**Comment by mdelapenya** [comment]
We can use the version your agent needs

**Comment by shuyangzhou** [comment]
@mdelapenya I was not clear enough, the current version of cobertura 1.9.4.1 does not support JDK7 only syntax sugar. So on report generating, it will fail.

I am just wondering what is the goal for adding code coverage support for module, of course it can always be helpful, but any code coverage tool by itself can not really do much.

Let's say we have it, you run it once, it says something is 85% covered, which in average is a good coverage. On the next day, someone changes something, we rerun the code coverage, it says 82% covered, which is a dropping. It is a bad thing, but what can we do about it, literally nothing. Then this is really not something we must have, at least not right away.

In core, the way we use code coverage, is not based on its report. We have the tool called CodeCoverageAssertor which you must already be very familiar with. We let the test to guard itself, only if it is already 100% covered, then any further change that drops the coverage will be rejected. The process is automated by CI, no human interference is required. Dropping coverage of a 100% covered test means breaking it.

Again, adding jdk7 report support is on my todo list, just with a low priority, I will get to it eventually. Can we wait until then to add code coverage support for modules? I really don't see this as a critical thing that needs to be done right away, as we can not really benefit from it.

**Comment by mdelapenya** [comment]
Hey @shuyangzhou, I understand your thoughts about cobertura library version, and agree too that those classes need 100% coverage not to break them. But remember that 100% coverage does not mean that a piece of software is not broken! :)

Related to the coverage assertor, it's the same as we talked about for PMD: it can be used to force a pull not to be merged, I totally agree with that, but maybe embedding it into a test is not the best idea, because a test and a static code analysis are semantically different. Maybe having N-phases validation (test->pmd->cobertura->...->xyzTool) will help, but at least, developers inside and outside Liferay will be able to execute common-use tools to measure what they need: coverage, pmd, findbugs, etc, and not having to pass through the test phase for that.

I.e. Jenkins has plugins for those PMD-FindBugs tools and you can fail the build setting up your quality gates: more/less than X of Blah attribute will fail the build.

More over, generating the artifacts those tools generate (usually XML), they will be able to send them to the reporting tool they want: Sonarqube, Jenkins + plugins, etc, again not reading a test result, just executing their single commands, which is simpler. And both options must not be mutually exclusive :)

Understanding that there are more important things to work on than this, if we want to provide quality to our products, and to provide external developers tools to measure their liferay code quality, we must prioritize not this task but tasks in this direction. Look that I intentionally said products, because there will be more and more Liferay teams using their own repos, like Audience Targeting, and we need to provide tools for them. In fact, this pull was originally created for their repo (SDK on 6.2.x), but we decided to contribute it to master not to isolate the improvement.

If you think we can work on it cooperating with you, please let us know.

**Comment by brianchandotcom** [comment]
@mdelapenya @cgoncas @shuyangzhou 

Cristina should be flying to the US next month, can we make this one of her goals for the 2 weeks? She can work with Shuyang and go over this with him then.

Thx!

**Pull request closed without merging**
