### PR TITLE
LPS-56308 Remove google-apps-configuration-hook as it has been merged into document-library-google-docs

### PR DESCRIPTION
**Pull request by izaera**
WARNING - ACHTUNG - CUIDADIN: 

Do not merge this pull before https://github.com/brianchandotcom/liferay-portal/pull/27439

Cheers,
Ivan

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/614e9b293b...f3237b52c5

**Comment by brianchandotcom** [comment]
You forgot CUIDADO....

**Comment by brianchandotcom** [comment]
Also, I didn't backport this to ee-6.2.x, but the LPS shows that it affects 6.2.x, can you send me something there if necessary? Thx!

**Comment by izaera** [comment]
No, I didn't forget CUIDADO, just wrote CUIDADIN, which is something like "little cuidado" ;-).

**Comment by izaera** [comment]
Will look at 6.2 now.

**Comment by izaera** [comment]
This doesn't affect 6.2: the LPS in the commit is wrong. It says 56308 but it should be 56038 :-(.

**Pull request closed without merging**
