### PR TITLE
LPS-52916

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/0302533b1c...7eda0b9cf9

**Comment by brianchandotcom** [comment]
Can you send a backport to ee-6.2.x if it's a bug fix? Thanks @pei-jung !

**Comment by pei-jung** [comment]
Hi Brian,

ee-6.2.x uses an older version of bootstrap, so some of these changes cant be directly backported. I have a separate fix for this on ee-6.2.x, and it's under review now. Thanks!

**Comment by brianchandotcom** [comment]
Thanks :) for everything...

**Pull request closed without merging**
