### PR TITLE
LPS-62208

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-62208.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/013c93b76b...9c14b66e40

**Comment by brianchandotcom** [comment]
@jonmak08 can you send one to ee-7.0.x too? Thx.

**Comment by jonmak08** [comment]
Hey @brianchandotcom,

Sure thing!

**Comment by jonmak08** [comment]
Pull request to ee-7.0.x plugins: https://github.com/brianchandotcom/liferay-plugins-ee/pull/16952

**Pull request closed without merging**
