### PR TITLE
LPS-56573 watch task update

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@natecavanaugh here's the feature you wanted

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/eb88dbcdb5...3a52da8af7

**Comment by brianchandotcom** [comment]
Sorry this took so long bebe. See upstream for my changes. Thx @david-truong

**Comment by brianchandotcom** [comment]
@david-truong can you double check that it still works with my changes? Thx.

**Pull request closed without merging**
