### PR TITLE
LPS-55228 Remove stale MessageBus reference - fix Solr OSGi not starting

### PR DESCRIPTION
**Pull request by arboliveira**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/b921a1d5d5...338377786d

**Comment by brianchandotcom** [comment]
@mhan810 there may be more like this. See fix from @arboliveira .. Thx.

**Comment by mhan810** [comment]
Yep Andre sent me a pr before fwding to you.  I'll take a look @ the other
plugins



*From:* Brian Chan [mailto:notifications@github.com]
*Sent:* Tuesday, May 12, 2015 2:13 PM
*To:* brianchandotcom/liferay-plugins
*Cc:* Michael Han
*Subject:* Re: [liferay-plugins] LPS-55228 Remove stale MessageBus
reference - fix Solr OSGi not starting (#4581)



@mhan810 <https://github.com/mhan810> there may be more like this. See fix
from @arboliveira <https://github.com/arboliveira> .. Thx.

--
Reply to this email directly or view it on GitHub
<https://github.com/brianchandotcom/liferay-plugins/pull/4581#issuecomment-101391196>
.

**Comment by mhan810** [comment]
@brianchandotcom actually, we're fine, Solr is the only one using blueprint w/ the OSGISearchEngineConfigurator.  It will be converted over to DS shortly

**Pull request closed without merging**
