### PR TITLE
LPS-61654

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-61654.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/14f1b20884...58bac9e525

**Comment by brianchandotcom** [comment]
@jonmak08 please backport as necessary

**Comment by jonmak08** [comment]
Ok thanks @brianchandotcom!

**Pull request closed without merging**
