### PR TITLE
LPS-53768 Kaleo new features

### PR DESCRIPTION
**Pull request by ethanbustad**
See https://github.com/brianchandotcom/liferay-portal/pull/27106.

cc @mhan810 @marcellustavares

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/e8996494e6...06d416ee78

**Comment by brianchandotcom** [comment]
@ethanbustad can you see my changes and retest? @awagnerur @mhan810 thx.

**Comment by ethanbustad** [comment]
@brianchandotcom looks good to me, and my simple test still works

**Pull request closed without merging**
