### PR TITLE
LPS-53001 Adapt resources-importer-web to Wiki's OSGi extraction

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
@brianchandotcom For this PR to work you need to publish JARs for wiki-api and wiki-service versions 1.0.0-SNAPSHOT in our corporate repo. Thx.

**Comment by brianchandotcom** [comment]
@izaera I merged in your changes, but wiki-navigation-portlet and resources-importer-web still do not work. Not sure why, but it's late in the day so I merged it anyways, but need you to send me another pull tomorrow.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/80e5ba425e...a88c4e0b1c

**Comment by izaera** [comment]
@brianchandotcom This was not merged in, finally. Don't know what happenned. I will check those portlets you say still fail and resend.

**Comment by brianchandotcom** [comment]
Sorry, I forgot to push it upstream. I just did. So the other plugins work minus those 2.

**Pull request closed without merging**
