### PR TITLE
[See desc] LPS-67762 LPS-67763 Remove Technorati service too since it's no longer offered

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @brianchandotcom this pull has 2 different LPS but they are very related, that's why they're both in this pull.
Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @mwilliams2014 @sharonchoi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/3fae0c5bb0...ade71e304b

**Comment by brianchandotcom** [comment]
@sergiogonzalez can you guys backport as needed? thx.

**Comment by brianchandotcom** [comment]
@sergiogonzalez specifically for 6.2 if necessary. I already did 7. Thx.

**Pull request closed without merging**
