### PR TITLE
LPS-61557 ant format-source

### PR DESCRIPTION
**Pull request by adolfopa**
See backport https://github.com/brianchandotcom/liferay-plugins-ee/pull/16404

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/7bd031fe91...d0571151c0

**Comment by brianchandotcom** [comment]
@adolfopa I reverted your last SF commit. Those classes are supposed to be autogenerated but aren't. I'm going to dig in and see what's wrong.

**Comment by brianchandotcom** [comment]
@adolfopa nvm, I just went with your solution. Those were manually done.

**Pull request closed without merging**
