### PR TITLE
LPS-55740 Upgrade Struts to 1.3.10

### PR DESCRIPTION
**Pull request by samuelkong**
/cc @yxingwu

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:retest

**Comment by samuelkong** [comment]
Test is failing because we added new JARs to portal and it looks like the plugins compiler isn't aware of these new JARs.

**Comment by samuelkong** [comment]
Test is failing because we added new JARs to portal and it looks like the plugins compiler isn't aware of these new JARs in portal.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/cc301a84d6...31fc3b3d60

**Pull request closed without merging**
