### PR TITLE
LPS-64192 Alloy Portlet - build alloy portlet portlet url

### PR DESCRIPTION
**Pull request by wesleygong**

### CODE REVIEW

**Comment by wesleygong** [comment]
@brianchandotcom Already pushed up liferay-plugins-ee/ee-6.2.x branch

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/74f0937721...f0184fc6a5

**Comment by brianchandotcom** [comment]
@wesleygong @vishal-reddy you should have used the same ticket (LRIS-17365) as in ee-6.2.x. It's weird that it's different.

**Comment by wesleygong** [comment]
@brianchandotcom do you have a preference when committing stuff to liferay-plugins? Since it's public, you would like us to use LPS tickets, correct?

**Pull request closed without merging**
