### PR TITLE
LRQA-37719

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/4f3217392a...3ccb4db4af

**Comment by brianchandotcom** [comment]
@Ithildir will you send this to ee-6.2.x? Thx.

**Comment by Ithildir** [comment]
Hi @brianchandotcom,
This pull was to synchronize the Gradle files between `master` and `ee-6.2.x`, now they're exactly the same.

**Pull request closed without merging**
