### PR TITLE
LPS-60882 Use word-wrap instead.

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
Sorry, closed it by mistake

**Comment by adolfopa** [comment]
See backport https://github.com/brianchandotcom/liferay-plugins-ee/pull/15946

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/83ec410c5d...3502d526dc

**Pull request closed without merging**
