### PR TITLE
LPS-52115

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@marcellustavares, @hhuijser fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/52a89e07cb...002ef43bc2

**Comment by brianchandotcom** [comment]
Hey guys,

Please resend. Half the upgrade code is not needed. When you regen, if you have a new service.properties increment number, it'll add the new columns. It may even change the column type.

See ServiceComponentLocalServiceImpl#upgradeModels

It may auto do it.

Thx

**Comment by daviddotzhang** [comment]
Hey guys,

sorry for the late reply.

:+1: 
@brianchandotcom  thanks for the clarification, I have tested what you have said. the columns have been added by increasing the "build number",also it will change column type. 

Now I will resend the pull request  by using:

LPS-52115 make database columns consistent

LPS-52115 regen svcs

David.

**Pull request closed without merging**
