### PR TITLE
LPS-55267 update portlet URLs

### PR DESCRIPTION
**Pull request by juliocamarero**
Hi Brian, 

we can't make a nicer integration until these portlets are migrated to OSGI. The collab team will do this soon, so we will help them to migrate this.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@ealonso can you resend? I see that they are defined in PortleKeys in core. That way, we can see a list and later abstract them out. If we put it here, we won't remember to do it.

Thx

**Comment by brianchandotcom** [comment]
@ealonso See com.liferay.portal.util.PortletKeys.NESTED_PORTLETS

**Comment by brianchandotcom** [comment]
@ealonso I did a temp fix in a83875b218e0cf9ced5acf8bf49b60a0c0d0b140 to get things to compile, but can you resend a fix for the struts_action and other things that need to be updated? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/a83875b218...acd99d4aec

**Comment by brianchandotcom** [comment]
@ealonso I just went ahead and did it. Please review my merge. Thx!

**Comment by ealonso** [comment]
Thanks you very much!!

**Pull request closed without merging**
