### PR TITLE
LPS-60927 ant build-service

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/a4bdf2729b...83ec410c5d

**Comment by brianchandotcom** [comment]
@adolfopa please see my changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
@adolfopa please backport. Thx.

**Pull request closed without merging**
