### PR TITLE
LPS-64813 Use correct path

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
It shoudl be in src/content, not classes/content since that's a temp build dir.

**Comment by brianchandotcom** [comment]
@csierra I pushed the proper fix in upstream. Fyi.

**Comment by csierra** [comment]
ooops... sure Brian... I tried that it worked on my machine and never looked back :sweat_smile: 

thanks for correcting it!

**Pull request closed without merging**
