### PR TITLE
LPS-53704 Using PreparedStatement

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
Hey Brian.

Here we use PreparedStatement as requested by https://github.com/brianchandotcom/liferay-plugins/pull/4326 However, I have not made use of the @DeleteAfterRun annotation. The requested JUnit rule does not work with plugins, as stated in https://issues.liferay.com/browse/LPS-54258. If the current, manual solution is not up to merging, we can remove the test altogether, just let  me know.

**Comment by brianchandotcom** [comment]
@brandizzi 

I merged this in, but can you make an LPS ticket and email @willnewbury and @shuyangzhou to see why the DelteAfterRun annotation is broken? @willnewbury just worked on it recently.

Thx. Also, please send me a backport to ee-6.2.x as you see fit.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/9b1eebbd25...bb335b537c

**Comment by shuyangzhou** [comment]
DeleteAfterTestRun is not working because the tests are not using our arquillian extension, but the official one which does not understand junit rules.

Please see Polls test module to follow the example.

**Comment by brandizzi** [comment]
Hello @shuyangzhou. The class `com.liferay.arquillian.extension.junit.bridge.junit.Arquillian` is not accessible from plugins. If I try to use it, the integration tests do not compile.

**Comment by brandizzi** [comment]
(To avoid a lot of notifications here, I've posted the comment above at the ticket: https://issues.liferay.com/browse/LPS-54258?focusedCommentId=590033&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-590033)

**Comment by shuyangzhou** [comment]
You need to update your ivy.xml to use our extension, see polls-test.

**Comment by brandizzi** [comment]
I've updated the ivy.xml file and now Ant complains that no `bnd.bnd` file is available:

    [junit] Tests run: 0, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1,576 sec
    [junit] Tests run: 0, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1,576 sec
    [junit]
    [junit] Testcase: com.liferay.calendar.hook.upgrade.v1_0_1.UpgradeCalendarTest:     Caused an ERROR
    [junit] java.lang.IllegalStateException: java.lang.IllegalStateException: java.io.FileNotFoundException: bnd.bnd (Arquivo ou diretório não encontrado)
    [junit] java.lang.RuntimeException: java.lang.IllegalStateException: java.lang.IllegalStateException: java.io.FileNotFoundException: bnd.bnd (Arquivo ou diretório não encontrado)
    [junit]     at org.arquillian.liferay.deploymentscenario.BndDeploymentScenarioGenerator.generate(BndDeploymentScenarioGenerator.java:162)
    [junit]     at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.generateDeployment(DeploymentGenerator.java:79)

Do I have to convert all the plugin into a OSGi module?

**Comment by shuyangzhou** [comment]
That's the org.arquillian.liferay.deploymentscenario.BndDeploymentScenarioGenerator, you should ping @cgoncas and @csierra

Seems BndDeploymentScenarioGenerator is assuming the current deployment is osgi bundle which is not the case for plugins. It should at least check the bnd file's existence before trying to read it.

**Comment by csierra** [comment]
hey @brandizzi
if you are in a plugins scenario you should not use arquillian-deployment-generator-bnd. As Shuyang says, that's only for OSGi bundles. Try using ```<dependency conf="test->default" name="com.liferay.ant.arquillian" org="com.liferay" rev="1.0.0" />``` to use the extension for creating the test bundle from the SDK instead of from BND. You should also use ```<dependency conf="test->default" name="arquillian-tomcat-remote-7" org="org.jboss.arquillian.container" rev="1.0.0.CR6" />``` because you are not deploying an OSGi bundle, but a regular war file, so you can use the existing arquillian tomcat extension.

**Comment by csierra** [comment]
hey @brandizzi, @shuyangzhou 
I see that junit-bridge is currently pulling bnd-deployment-scenario-generator and arquillian-container-liferay, so currently you are not going to be able to use it from the plugins.

@shuyangzhou would it be possible to not pull those packages in the junit-bridge and pull them in the tests that need them? that way I guess we could use the junit-bridge also in legacy plugins.

**Comment by shuyangzhou** [comment]
This change was requested by @brianchandotcom at LPS-53994, the goal is to simplify the ivy.xml dependencies declaration. To free developer from remembering and figuring out what needs to be declared, but just simply always using the junit bridge extension only.

Is that possible from BndDeploymentScenarioGenerator, you make it checks the existence of bnd file first? If there is no bnd file sitting there, simply let it passing through without changing the archive? That should be a defensive harmless change, and making it compatible with plugins.

If for any reason we can not do that, @brianchandotcom we will have to undo LPS-53994, to force developer to declare exactly what they need to use.

**Comment by csierra** [comment]
I am afraid that that would not be the only concern. Also the deployment strategy that junit-bridge is currenlty enforcing is OSGi bundle. Also nobody knows how to build a proper test archive, because there is no deployment scenario generator, so letting it pass would not solve it. 

What we could do, though, to fulfill LPS-53994, is to create an umbrella dependency for OSGi modules that brings together junit-bridge, arquillian-container-liferay and bnd-deployment-scenario-generator.
This way we could use that "one dep to bring them all" in the OSGi modules to save keep the ivy.xml simple while keeping the junit-rule usable from other scenarios. 

What do you guys think?

**Comment by shuyangzhou** [comment]
That sounds like a reasonable solution!

**Comment by csierra** [comment]
:smile: :+1:

**Comment by shuyangzhou** [comment]
@csierra do you mind to do this? My team is under load now, I won't have time for it any time soon.

**Comment by csierra** [comment]
I will bring this up today. Not my call though...

**Comment by brandizzi** [comment]
Thanks @csierra and @shuyangzhou!

Is there some estimation of when the JUnit bridge will be working on plugins? If it is going to take some time, I'll keep writing tests without @DeleteAfterRun annotations to update them later. If the bridge will be available soon, however, I'll wait until it is done.

**Comment by csierra** [comment]
Hey @brandizzi, @shuyangzhou 

we would not mind to take care of this. We have been discussing here but we can't tell when we are going to be able to tackle this.  

As soon as one of us finishes our current task this will be the next. 

Bests.

**Pull request closed without merging**
