### PR TITLE
LPS-52680

### PR DESCRIPTION
**Pull request by johnnyhowey**
the new variable start needs to be global, this is why we added the portletnamespce in front. We change the do while loop to while loop. The code is much cleaner.

### CODE REVIEW

**Comment by johnnyhowey** [comment]
@IstvanD please send the backport after this is approved

**Comment by IstvanD** [comment]
@johnnyhowey I will.
Thanks.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/0dd3248fa1...6b069cd8a2

**Comment by brianchandotcom** [comment]
@IstvanD please see my changes and backport

**Pull request closed without merging**
