### PR TITLE
LPS-56288

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
cc @nhpatt

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/ac2dc7f9e5...c7819234b6

**Comment by brianchandotcom** [comment]
@brunofarache can you see my changes in upstream and see if they are OK (i.e. still work)

**Comment by brunofarache** [comment]
@brianchandotcom just checked it works.

**Pull request closed without merging**
