### PR TITLE
LPS-54326 apply bnd jsp plugin to SDK

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
Once this goes in and update the SDK in liferay-portal, we just need to add the `com.liferay.ant.bnd.plugin.JSPAnalyzerPlugin` plugin to the `-plugin` build property.

**Comment by rotty3000** [comment]
after that I'll update all the modules that use JSPs to remove the manual `Require-Capability` headers

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-plugins/compare/e3f535823f...53a066001e

**Comment by brianchandotcom** [comment]
Done. Pushed up. Thx Ray!

**Pull request closed without merging**
